"""add table to store contract drafts

Revision ID: 00d7a9831de0
Revises: 81efbf98020a
Create Date: 2025-05-25 16:24:56.980194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00d7a9831de0'
down_revision: Union[str, None] = '81efbf98020a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractdrafts',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('clientid', sa.UUID(), nullable=True),
    sa.Column('bikeid', sa.UUID(), nullable=True),
    sa.Column('workinguserid', sa.UUID(), nullable=True),
    sa.Column('checkinguserid', sa.UUID(), nullable=True),
    sa.Column('depositcollectinguserid', sa.UUID(), nullable=True),
    sa.Column('startdate', sa.Date(), server_default=sa.text("(current_date at time zone 'utc')"), nullable=False),
    sa.Column('enddate', sa.Date(), server_default=sa.text("(current_date at time zone 'utc' + make_interval(months => 6))"), nullable=False),
    sa.Column('depositamountcollected', sa.Integer(), nullable=True),
    sa.Column('conditionofbike', sa.String(length=20), nullable=True),
    sa.Column('contracttype', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bikeid'], ['bikes.id'], ),
    sa.ForeignKeyConstraint(['checkinguserid'], ['users.id'], ),
    sa.ForeignKeyConstraint(['clientid'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['depositcollectinguserid'], ['users.id'], ),
    sa.ForeignKeyConstraint(['workinguserid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contractdrafts_enddate'), 'contractdrafts', ['enddate'], unique=False)
    op.create_index(op.f('ix_contractdrafts_id'), 'contractdrafts', ['id'], unique=False)
    op.create_index(op.f('ix_contractdrafts_startdate'), 'contractdrafts', ['startdate'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contractdrafts_startdate'), table_name='contractdrafts')
    op.drop_index(op.f('ix_contractdrafts_id'), table_name='contractdrafts')
    op.drop_index(op.f('ix_contractdrafts_enddate'), table_name='contractdrafts')
    op.drop_table('contractdrafts')
    # ### end Alembic commands ###
