"""added permission scopes and user permissions

Revision ID: 0787b049962a
Revises: c0dc35faf013
Create Date: 2025-05-15 15:58:18.155791

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0787b049962a'
down_revision: Union[str, None] = 'c0dc35faf013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissionscopes',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('route', sa.Text(), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissionscopes_id'), 'permissionscopes', ['id'], unique=False)
    op.create_table('userpermissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('userid', sa.UUID(), nullable=False),
    sa.Column('permissionscopeid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permissionscopeid'], ['permissionscopes.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_userpermissions_id'), 'userpermissions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_userpermissions_id'), table_name='userpermissions')
    op.drop_table('userpermissions')
    op.drop_index(op.f('ix_permissionscopes_id'), table_name='permissionscopes')
    op.drop_table('permissionscopes')
    # ### end Alembic commands ###
