"""toggle gradual availability

Revision ID: 07c7bf717e4b
Revises: 3106888ce791
Create Date: 2024-12-26 14:33:56.383261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07c7bf717e4b'
down_revision: Union[str, None] = '3106888ce791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointmentgeneralsettings', sa.Column('gradualavailability', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointmentgeneralsettings', 'gradualavailability')
    # ### end Alembic commands ###
