"""added tag to expenses and expense tags table

Revision ID: 09bb4fe80b9e
Revises: 07c7bf717e4b
Create Date: 2024-12-30 18:27:00.292029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09bb4fe80b9e'
down_revision: Union[str, None] = '07c7bf717e4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    expense_table = op.create_table('expensetags',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )

    # insert a default entry
    op.bulk_insert(expense_table, [{"id": "workshop", "description": "Expenses directly related to workshop operations."}])

    # use default tag for new column, then remove default value
    op.add_column('expenses', sa.Column('tagId', sa.String(length=20), nullable=False, server_default=sa.text("'workshop'")))
    op.alter_column('expenses', 'tagId', server_default=None)

    op.create_foreign_key(None, 'expenses', 'expensetags', ['tagId'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'tagId')
    op.drop_table('expensetags')
    # ### end Alembic commands ###
