"""#303 deposit amount and collector can be null

Revision ID: 09c70816ae58
Revises: 4ff1d6bdf35f
Create Date: 2026-02-16 20:12:32.990216

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '09c70816ae58'
down_revision: Union[str, None] = '4ff1d6bdf35f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'depositcollectinguserid',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('contracts', 'depositamountcollected',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'depositamountcollected',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('contracts', 'depositcollectinguserid',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
