"""#312 added item catalogue

Revision ID: 0a0a38e50e42
Revises: 250a553c9395
Create Date: 2026-02-24 20:33:58.713718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a0a38e50e42'
down_revision: Union[str, None] = '250a553c9395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('catalogueitemphotos',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('photocontenttype', sa.Text(), nullable=True),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogueitemphotos_id'), 'catalogueitemphotos', ['id'], unique=False)
    op.create_table('catalogueitems',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('make', sa.String(length=60), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('purchaseprice', sa.Integer(), nullable=True),
    sa.Column('recommendedretailprice', sa.Integer(), nullable=True),
    sa.Column('available', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('createdon', sa.DateTime(), server_default=sa.text("(current_timestamp at time zone 'utc')"), nullable=False),
    sa.Column('photoid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['photoid'], ['catalogueitemphotos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogueitems_id'), 'catalogueitems', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalogueitems_id'), table_name='catalogueitems')
    op.drop_table('catalogueitems')
    op.drop_index(op.f('ix_catalogueitemphotos_id'), table_name='catalogueitemphotos')
    op.drop_table('catalogueitemphotos')
    # ### end Alembic commands ###
