"""#299 bikes have a rough value and a disposition

Revision ID: 10bebd9ef862
Revises: 616e4ec2b358
Create Date: 2026-02-26 22:15:30.892473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = '10bebd9ef862'
down_revision: Union[str, None] = '616e4ec2b358'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.execute("CREATE TYPE disposition AS ENUM ('RENTAL', 'SALE');")
    
    op.add_column('bikes', sa.Column('roughvalue', sa.Integer(), nullable=True))
    op.add_column('bikes', sa.Column('disposition', sa.Enum('RENTAL', 'SALE', name='disposition'), nullable=True))

    db = op.get_bind()

    db.execute(text("UPDATE bikes SET disposition = 'RENTAL'"))

    op.alter_column('bikes', 'disposition', nullable=False)
    
    db.execute(text("UPDATE bikes SET roughvalue = ("
                    "SELECT "
                    "   MAX(deposit) "
                    "FROM ("
                    "   SELECT"
                    "       t.deposit AS deposit"
                    "   FROM ("
                    "       SELECT "
                    "           MAX(tl.amount) AS deposit "
                    "       FROM bikes b "
                    "       LEFT JOIN contracts c ON c.bikeid=b.id "
                    "       LEFT JOIN transactionheaders th ON th.id=c.depositcollectedtransactionheaderid "
                    "       LEFT JOIN transactionlines tl ON tl.transactionheaderid = th.id "
                    "       WHERE b.id = bikes.id GROUP BY th.postedon ORDER BY th.postedon DESC LIMIT 1 "
                    "   ) t"
                    "   UNION ALL "
                    "   SELECT "
                    "       4000 AS deposit"
                    ") t)"))
    
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bikes', 'disposition')
    op.drop_column('bikes', 'roughvalue')
    op.execute("DROP TYPE disposition;")
    # ### end Alembic commands ###
