"""#339 restricted funds reimplementation

Revision ID: 1516f119340e
Revises: e9751436dae9
Create Date: 2026-08-29 13:16:16.560581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = '1516f119340e'
down_revision: Union[str, None] = 'e9751436dae9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funds',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('isactive', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('isdefault', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_funds_id'), 'funds', ['id'], unique=False)
    
    op.drop_constraint('accounts_restrictedtoprojectid_fkey', 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'restrictedtoprojectid')
    op.drop_table('projects')
    
    op.add_column('transactionlines', sa.Column('fundid', sa.UUID(), server_default=sa.text('NULL'), nullable=True))
    op.create_foreign_key(None, 'transactionlines', 'funds', ['fundid'], ['id'])

    db = op.get_bind()
    db.execute(text("INSERT INTO funds (name, description, isactive, isdefault) VALUES ('Unrestricted', 'Funds for normal operations', 't', 't');"))
    unrestrictedFundId = db.execute(text("SELECT id FROM funds WHERE name = 'Unrestricted'")).all()[0][0]
    if not unrestrictedFundId:
        raise Exception('something went wrong')
    db.execute(text(f"UPDATE transactionlines SET fundid = '{unrestrictedFundId}';"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("transactionlines_fundid_fkey", 'transactionlines', type_='foreignkey')
    op.drop_column('transactionlines', 'fundid')
    op.add_column('accounts', sa.Column('restrictedtoprojectid', sa.VARCHAR(length=20), server_default=sa.text('NULL::character varying'), autoincrement=False, nullable=True))
    op.create_table('projects',
                    sa.Column('id', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
                    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=False),
                    sa.Column('active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
                    sa.PrimaryKeyConstraint('id', name='projects_pkey')
                    )
    op.create_foreign_key('accounts_restrictedtoprojectid_fkey', 'accounts', 'projects', ['restrictedtoprojectid'], ['id'])

    op.drop_index(op.f('ix_funds_id'), table_name='funds')
    op.drop_table('funds')
    # ### end Alembic commands ###
