"""#310 posted details are on header not on lines

Revision ID: 1e8c3e0ac9c4
Revises: 4d1f1b5655c8
Create Date: 2026-02-15 23:23:14.621173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1e8c3e0ac9c4'
down_revision: Union[str, None] = '4d1f1b5655c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactionheaders', sa.Column('postedon', sa.DateTime(), nullable=True))
    op.add_column('transactionheaders', sa.Column('postedbyuserid', sa.UUID(), server_default=sa.text('NULL'), nullable=True))
    op.create_foreign_key(None, 'transactionheaders', 'users', ['postedbyuserid'], ['id'])
    op.drop_constraint('transactionlines_postedbyuserid_fkey', 'transactionlines', type_='foreignkey')
    op.drop_column('transactionlines', 'postedon')
    op.drop_column('transactionlines', 'postedbyuserid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactionlines', sa.Column('postedbyuserid', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('transactionlines', sa.Column('postedon', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_foreign_key('transactionlines_postedbyuserid_fkey', 'transactionlines', 'users', ['postedbyuserid'], ['id'])
    op.drop_constraint(None, 'transactionheaders', type_='foreignkey')
    op.drop_column('transactionheaders', 'postedbyuserid')
    op.drop_column('transactionheaders', 'postedon')
    # ### end Alembic commands ###
