"""#302 new expenses system starts with claims

Revision ID: 250a553c9395
Revises: aef9aced5d15
Create Date: 2026-02-19 22:55:00.056543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '250a553c9395'
down_revision: Union[str, None] = 'aef9aced5d15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expenseclaims',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('expensedate', sa.Date(), nullable=False),
    sa.Column('expensetransactionheaderid', sa.UUID(), nullable=False),
    sa.Column('reimbursementtransactionheaderid', sa.UUID(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('receiptfileid', sa.UUID(), server_default=sa.text('NULL'), nullable=False),
    sa.Column('receiptcontenttype', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['expensetransactionheaderid'], ['transactionheaders.id'], ),
    sa.ForeignKeyConstraint(['receiptfileid'], ['expenseReceipts.id'], ),
    sa.ForeignKeyConstraint(['reimbursementtransactionheaderid'], ['transactionheaders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenseclaims_id'), 'expenseclaims', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expenseclaims_id'), table_name='expenseclaims')
    op.drop_table('expenseclaims')
    # ### end Alembic commands ###
