"""326-bug-reporting-function

Revision ID: 289ab654eaa9
Revises: e93a9bf1ed35
Create Date: 2026-08-13 17:00:44.409993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '289ab654eaa9'
down_revision: Union[str, None] = 'e93a9bf1ed35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bugreports',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('reportedbyuserid', sa.UUID(), nullable=False),
    sa.Column('reportedat', sa.DateTime(), server_default=sa.text("(current_timestamp at time zone 'utc')"), nullable=False),
    sa.Column('pageaddress', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=False),
    sa.Column('consolehistory', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['reportedbyuserid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bugreports_id'), 'bugreports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bugreports_id'), table_name='bugreports')
    op.drop_table('bugreports')
    # ### end Alembic commands ###
