"""#192 store closing date instead of closed boolean

Revision ID: 29519339abb4
Revises: b6e19fd0aee6
Create Date: 2025-08-31 13:48:35.120095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29519339abb4'
down_revision: Union[str, None] = 'b6e19fd0aee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crimereports', sa.Column('closedon', sa.DateTime(), nullable=True))
    op.drop_column('crimereports', 'closed')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crimereports', sa.Column('closed', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('crimereports', 'closedon')
    # ### end Alembic commands ###
