"""index contract start and end date columns

Revision ID: 2b1bf0903a94
Revises: 09bb4fe80b9e
Create Date: 2025-02-01 17:59:45.398834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b1bf0903a94'
down_revision: Union[str, None] = '09bb4fe80b9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_contracts_enddate'), 'contracts', ['enddate'], unique=False)
    op.create_index(op.f('ix_contracts_startdate'), 'contracts', ['startdate'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contracts_startdate'), table_name='contracts')
    op.drop_index(op.f('ix_contracts_enddate'), table_name='contracts')
    # ### end Alembic commands ###
