"""Add index on appoinments startdatetime

Revision ID: 3106888ce791
Revises: 408c9e91d43a
Create Date: 2024-12-08 16:13:09.261695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3106888ce791'
down_revision: Union[str, None] = '408c9e91d43a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_appointments_startdatetime'), 'appointments', ['startdatetime'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_startdatetime'), table_name='appointments')
    # ### end Alembic commands ###
