"""#417 dashboard sorting index

Revision ID: 337edae0bdee
Revises: 5ce2a3ab5210
Create Date: 2026-09-05 21:08:20.364752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '337edae0bdee'
down_revision: Union[str, None] = '5ce2a3ab5210'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dashboards', sa.Column('index', sa.Integer(), autoincrement=True, nullable=False))
    op.create_unique_constraint(None, 'dashboards', ['index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dashboards', type_='unique')
    op.drop_column('dashboards', 'index')
    # ### end Alembic commands ###
