"""#333 get rid of contractdrafts table

Revision ID: 36b6e0d60049
Revises: e93a9bf1ed35
Create Date: 2026-08-15 14:20:10.563602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36b6e0d60049'
down_revision: Union[str, None] = 'e93a9bf1ed35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("""CREATE OR REPLACE VIEW orphanedclients AS SELECT c.id
                                                 FROM clients c
                                                          LEFT JOIN (
                                                     SELECT count(a.id) num
                                                          ,a.clientid
                                                     FROM appointments a
                                                     GROUP BY a.clientid
                                                 ) appcounts ON appcounts.clientid = c.id
                                                          LEFT JOIN (
                                                     SELECT count(con.id) num
                                                          ,con.clientid
                                                     FROM contracts con
                                                     GROUP BY con.clientid
                                                 ) concounts ON concounts.clientid = c.id
                                                 WHERE
                                                     appcounts.num IS NULL AND
                                                     concounts.num IS NULL;""")

    op.execute("""CREATE OR REPLACE VIEW orphanedbikes AS SELECT b.id
                                                          FROM bikes b
                                                                   LEFT JOIN (
                                                              SELECT count(con.id) num
                                                                   ,con.bikeid
                                                              FROM contracts con
                                                              GROUP BY con.bikeid
                                                          ) concounts ON concounts.bikeid = b.id
                                                          WHERE
                                                              concounts.num IS NULL;""")


    op.add_column('contracts', sa.Column('isdraft', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False))
    op.execute("""
    UPDATE contracts SET isdraft = false;
    """)
    op.alter_column('contracts', 'clientid',
                    existing_type=sa.UUID(),
                    nullable=True)
    op.alter_column('contracts', 'bikeid',
                    existing_type=sa.UUID(),
                    nullable=True)
    op.alter_column('contracts', 'workinguserid',
                    existing_type=sa.UUID(),
                    nullable=True)
    op.alter_column('contracts', 'checkinguserid',
                    existing_type=sa.UUID(),
                    nullable=True)
    op.alter_column('contracts', 'startdate',
                    existing_type=sa.DATE(),
                    nullable=True,
                    existing_server_default=sa.text("(CURRENT_DATE AT TIME ZONE 'utc'::text)"))
    op.alter_column('contracts', 'enddate',
                    existing_type=sa.DATE(),
                    nullable=True,
                    existing_server_default=sa.text("((CURRENT_DATE AT TIME ZONE 'utc'::text) + make_interval(months => 6))"))
    op.alter_column('contracts', 'conditionofbike',
                    existing_type=sa.VARCHAR(length=20),
                    nullable=True)
    op.alter_column('contracts', 'contracttype',
                    existing_type=sa.VARCHAR(length=20),
                    nullable=True)
    op.drop_constraint('contracts_depositreturninguserid_fkey', 'contracts', type_='foreignkey')
    op.drop_constraint('contracts_depositcollectinguserid_fkey', 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'depositreturninguserid')
    op.drop_column('contracts', 'depositamountcollected')
    op.drop_column('contracts', 'depositamountreturned')
    op.drop_column('contracts', 'depositcollectinguserid')

    op.execute("""
               INSERT INTO contracts (id, clientid, bikeid, workinguserid, checkinguserid, contracttype, conditionofbike, notes, startdate, enddate, isdraft) 
               SELECT id, clientid, bikeid, workinguserid, checkinguserid, contracttype, conditionofbike, notes, startdate, enddate, true as isdraft FROM contractdrafts;
               """)
    op.execute("""
           UPDATE transactionheaders set contractid = (SELECT id FROM contractdrafts WHERE depositcollectedtransactionheaderid = transactionheaders.id ) WHERE contractid IS NULL AND event='deposit_collected';
           """)
    
    
    
    op.drop_index('ix_contractdrafts_enddate', table_name='contractdrafts')
    op.drop_index('ix_contractdrafts_id', table_name='contractdrafts')
    op.drop_index('ix_contractdrafts_startdate', table_name='contractdrafts')
    op.drop_table('contractdrafts')
    
    op.execute("UPDATE contracts SET enddate = startdate + interval '6 months' WHERE enddate < startdate")
    op.create_check_constraint('contracts_enddateAfterstartdate', 'contracts', 'enddate > startdate')
    op.create_check_constraint('contracts_isdraftOrClientid', 'contracts', 'isdraft = true OR clientid IS NOT NULL')
    op.create_check_constraint('contracts_isdraftOrBikeid', 'contracts', 'isdraft = true OR bikeid IS NOT NULL')
    op.create_check_constraint('contracts_isdraftOrWorkinguserid', 'contracts', 'isdraft = true OR workinguserid IS NOT NULL')
    op.create_check_constraint('contracts_isdraftOrCheckinguserid', 'contracts', 'isdraft = true OR checkinguserid IS NOT NULL')
    op.create_check_constraint('contracts_isdraftOrStartdate', 'contracts', 'isdraft = true OR startdate IS NOT NULL')
    op.create_check_constraint('contracts_isdraftOrEnddate', 'contracts', 'isdraft = true OR enddate IS NOT NULL')
    op.create_check_constraint('contracts_isdraftOrConditionofbike', 'contracts', 'isdraft = true OR conditionofbike IS NOT NULL')
    op.create_check_constraint('contracts_isdraftOrContracttype', 'contracts', 'isdraft = true OR contracttype IS NOT NULL')

    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractdrafts',
                    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
                    sa.Column('clientid', sa.UUID(), autoincrement=False, nullable=True),
                    sa.Column('bikeid', sa.UUID(), autoincrement=False, nullable=True),
                    sa.Column('workinguserid', sa.UUID(), autoincrement=False, nullable=True),
                    sa.Column('checkinguserid', sa.UUID(), autoincrement=False, nullable=True),
                    sa.Column('depositcollectinguserid', sa.UUID(), autoincrement=False, nullable=True),
                    sa.Column('startdate', sa.DATE(), server_default=sa.text("(CURRENT_DATE AT TIME ZONE 'utc'::text)"), autoincrement=False, nullable=False),
                    sa.Column('enddate', sa.DATE(), server_default=sa.text("((CURRENT_DATE AT TIME ZONE 'utc'::text) + make_interval(months => 6))"), autoincrement=False, nullable=False),
                    sa.Column('depositamountcollected', sa.INTEGER(), autoincrement=False, nullable=True),
                    sa.Column('conditionofbike', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
                    sa.Column('contracttype', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
                    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
                    sa.Column('depositcollectedtransactionheaderid', sa.UUID(), autoincrement=False, nullable=True),
                    sa.ForeignKeyConstraint(['bikeid'], ['bikes.id'], name='contractdrafts_bikeid_fkey'),
                    sa.ForeignKeyConstraint(['checkinguserid'], ['users.id'], name='contractdrafts_checkinguserid_fkey'),
                    sa.ForeignKeyConstraint(['clientid'], ['clients.id'], name='contractdrafts_clientid_fkey'),
                    sa.ForeignKeyConstraint(['depositcollectedtransactionheaderid'], ['transactionheaders.id'], name='contractdrafts_depositcollectedtransactionheaderid_fkey'),
                    sa.ForeignKeyConstraint(['depositcollectinguserid'], ['users.id'], name='contractdrafts_depositcollectinguserid_fkey'),
                    sa.ForeignKeyConstraint(['workinguserid'], ['users.id'], name='contractdrafts_workinguserid_fkey'),
                    sa.PrimaryKeyConstraint('id', name='contractdrafts_pkey')
                    )
    op.create_index('ix_contractdrafts_startdate', 'contractdrafts', ['startdate'], unique=False)
    op.create_index('ix_contractdrafts_id', 'contractdrafts', ['id'], unique=False)
    op.create_index('ix_contractdrafts_enddate', 'contractdrafts', ['enddate'], unique=False)
    
    
    
    op.execute("""
        INSERT INTO contractdrafts (id, clientid, bikeid, workinguserid, checkinguserid, contracttype, conditionofbike, notes, startdate, enddate) 
        SELECT id, clientid, bikeid, workinguserid, checkinguserid, contracttype, conditionofbike, notes, startdate, enddate FROM contracts where isdraft = true;
    """)
    
    op.execute("""
        UPDATE contractdrafts SET depositcollectedtransactionheaderid=(SELECT id FROM transactionheaders WHERE transactionheaders.contractid=contractdrafts.id);
    """)
    op.execute("""
        UPDATE transactionheaders SET contractid=NULL WHERE contractid IN (SELECT id FROM contractdrafts);
    """)
    
    op.execute("""
        DELETE FROM contracts WHERE isdraft = true;
    """)
    
    op.add_column('contracts', sa.Column('depositcollectinguserid', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('depositamountreturned', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('depositamountcollected', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('depositreturninguserid', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('contracts_depositcollectinguserId_fkey', 'contracts', 'users', ['depositcollectinguserid'], ['id'])
    op.create_foreign_key('contracts_depositreturninguserId_fkey', 'contracts', 'users', ['depositreturninguserid'], ['id'])

    op.drop_constraint('contracts_isdraftOrContracttype', 'contracts', type_='check')
    op.drop_constraint('contracts_isdraftOrConditionofbike', 'contracts', type_='check')
    op.drop_constraint('contracts_isdraftOrEnddate', 'contracts', type_='check')
    op.drop_constraint('contracts_isdraftOrStartdate', 'contracts', type_='check')
    op.drop_constraint('contracts_isdraftOrCheckinguserid', 'contracts', type_='check')
    op.drop_constraint('contracts_isdraftOrWorkinguserid', 'contracts', type_='check')
    op.drop_constraint('contracts_isdraftOrBikeid', 'contracts', type_='check')
    op.drop_constraint('contracts_isdraftOrClientid', 'contracts', type_='check')
    op.drop_constraint('contracts_enddateAfterstartdate', 'contracts', type_='check')
    
    op.alter_column('contracts', 'contracttype',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('contracts', 'conditionofbike',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('contracts', 'enddate',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text("((CURRENT_DATE AT TIME ZONE 'utc'::text) + make_interval(months => 6))"))
    op.alter_column('contracts', 'startdate',
               existing_type=sa.DATE(),
               nullable=False,
               existing_server_default=sa.text("(CURRENT_DATE AT TIME ZONE 'utc'::text)"))
    op.alter_column('contracts', 'checkinguserid',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('contracts', 'workinguserid',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('contracts', 'bikeid',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('contracts', 'clientid',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('contracts', 'isdraft')
    

    op.execute("""CREATE OR REPLACE VIEW orphanedbikes AS SELECT b.id
                                               FROM bikes b
                                                        LEFT JOIN (
                                                   SELECT count(con.id) num
                                                        ,con.bikeid
                                                   FROM contracts con
                                                   GROUP BY con.bikeid
                                               ) concounts ON concounts.bikeid = b.id
                                                        LEFT JOIN (
                                                   SELECT count(condraft.id) num
                                                        ,condraft.bikeid
                                                   FROM contractdrafts condraft
                                                   GROUP BY condraft.bikeid
                                               ) condraftcounts ON condraftcounts.bikeid = b.id
                                               WHERE
                                                   concounts.num IS NULL AND
                                                   condraftcounts IS NULL;""")

    op.execute("""CREATE OR REPLACE VIEW orphanedclients AS SELECT c.id
                                                 FROM clients c
                                                          LEFT JOIN (
                                                     SELECT count(a.id) num
                                                          ,a.clientid
                                                     FROM appointments a
                                                     GROUP BY a.clientid
                                                 ) appcounts ON appcounts.clientid = c.id
                                                          LEFT JOIN (
                                                     SELECT count(con.id) num
                                                          ,con.clientid
                                                     FROM contracts con
                                                     GROUP BY con.clientid
                                                 ) concounts ON concounts.clientid = c.id
                                                          LEFT JOIN (
                                                     SELECT count(condraft.id) num
                                                          ,condraft.clientid
                                                     FROM contractdrafts condraft
                                                     GROUP BY condraft.clientid
                                                 ) condraftcounts ON condraftcounts.clientid = c.id
                                                 WHERE
                                                     appcounts.num IS NULL AND
                                                     concounts.num IS NULL AND
                                                     condraftcounts IS NULL;""")
    # ### end Alembic commands ###
