"""#339 fundId cannot be null

Revision ID: 36eb89e30bbf
Revises: fe875a937c20
Create Date: 2026-09-08 23:03:52.842083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36eb89e30bbf'
down_revision: Union[str, None] = 'fe875a937c20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactionlines', 'fundid',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactionlines', 'fundid',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
