"""#301 create accounts table

Revision ID: 3ca41b71a5d0
Revises: a542b8e72d94
Create Date: 2026-02-15 12:02:19.252602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ca41b71a5d0'
down_revision: Union[str, None] = 'a542b8e72d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('owneruserid', sa.UUID(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('ownergroupid', sa.UUID(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('isinternal', sa.Boolean(), nullable=False),
    sa.Column('scheduledclosuredate', sa.DateTime(), nullable=True),
    sa.Column('closedon', sa.DateTime(), nullable=True),
    sa.Column('closedbyuserid', sa.UUID(), server_default=sa.text('NULL'), nullable=True),
    sa.Column('showinuis', sa.ARRAY(sa.String(length=20)), server_default=sa.text('ARRAY[]::text[]'), nullable=False),
    sa.ForeignKeyConstraint(['closedbyuserid'], ['users.id'], ),
    sa.ForeignKeyConstraint(['ownergroupid'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['owneruserid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_id'), 'accounts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_accounts_id'), table_name='accounts')
    op.drop_table('accounts')
    # ### end Alembic commands ###
