"""create view to identify orphaned clients

Revision ID: 4700ed9e9e05
Revises: e54aecec7d03
Create Date: 2025-08-09 17:42:36.842499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4700ed9e9e05'
down_revision: Union[str, None] = 'e54aecec7d03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""CREATE VIEW orphanedclients AS SELECT c.id
FROM clients c
LEFT JOIN (
        SELECT count(a.id) num
                ,a.clientid
        FROM appointments a
        GROUP BY a.clientid
        ) appcounts ON appcounts.clientid = c.id
LEFT JOIN (
        SELECT count(con.id) num
                ,con.clientid
        FROM contracts con
        GROUP BY con.clientid
        ) concounts ON concounts.clientid = c.id
LEFT JOIN (
        SELECT count(condraft.id) num
                ,condraft.clientid
        FROM contractdrafts condraft
        GROUP BY condraft.clientid
        ) condraftcounts ON condraftcounts.clientid = c.id
WHERE
        appcounts.num IS NULL AND
        concounts.num IS NULL AND
        condraftcounts IS NULL;""")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW orphanedclients;")
    # ### end Alembic commands ###
