"""some accounts can have negative balances

Revision ID: 4d1f1b5655c8
Revises: 3ccc014e4f37
Create Date: 2026-02-15 21:54:55.649725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d1f1b5655c8'
down_revision: Union[str, None] = '3ccc014e4f37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('isallowednegative', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'isallowednegative')
    # ### end Alembic commands ###
