"""cascade delete client duplicate when client is deleted

Revision ID: 4d56a78fc8bd
Revises: 96eddbbce619
Create Date: 2025-08-09 17:33:23.875011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d56a78fc8bd'
down_revision: Union[str, None] = '96eddbbce619'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('detectedpotentialclientduplicates_client1id_fkey', 'detectedpotentialclientduplicates', type_='foreignkey')
    op.drop_constraint('detectedpotentialclientduplicates_client2id_fkey', 'detectedpotentialclientduplicates', type_='foreignkey')
    op.create_foreign_key(None, 'detectedpotentialclientduplicates', 'clients', ['client1id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'detectedpotentialclientduplicates', 'clients', ['client2id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detectedpotentialclientduplicates', type_='foreignkey')
    op.drop_constraint(None, 'detectedpotentialclientduplicates', type_='foreignkey')
    op.create_foreign_key('detectedpotentialclientduplicates_client2id_fkey', 'detectedpotentialclientduplicates', 'clients', ['client2id'], ['id'])
    op.create_foreign_key('detectedpotentialclientduplicates_client1id_fkey', 'detectedpotentialclientduplicates', 'clients', ['client1id'], ['id'])
    # ### end Alembic commands ###
