"""#303 added deposit collected and settled transaction header ids to contract and draft

Revision ID: 4ff1d6bdf35f
Revises: 1e8c3e0ac9c4
Create Date: 2026-02-16 17:58:40.119263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ff1d6bdf35f'
down_revision: Union[str, None] = '1e8c3e0ac9c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contractdrafts', sa.Column('depositcollectiontransactionheaderid', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'contractdrafts', 'transactionheaders', ['depositcollectiontransactionheaderid'], ['id'])
    op.add_column('contracts', sa.Column('depositcollectiontransactionheaderid', sa.UUID(), nullable=True))
    op.add_column('contracts', sa.Column('depositsettledtransactionheaderid', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'contracts', 'transactionheaders', ['depositsettledtransactionheaderid'], ['id'])
    op.create_foreign_key(None, 'contracts', 'transactionheaders', ['depositcollectiontransactionheaderid'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'depositsettledtransactionheaderid')
    op.drop_column('contracts', 'depositcollectiontransactionheaderid')
    op.drop_constraint(None, 'contractdrafts', type_='foreignkey')
    op.drop_column('contractdrafts', 'depositcollectiontransactionheaderid')
    # ### end Alembic commands ###
