"""#358 add indices to relevant transaction header and line columns

Revision ID: 51e4fa786e3a
Revises: 25b0de41df38
Create Date: 2026-04-04 19:00:13.580236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51e4fa786e3a'
down_revision: Union[str, None] = '25b0de41df38'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_transactionheaders_contractid'), 'transactionheaders', ['contractid'], unique=False)
    op.create_index(op.f('ix_transactionheaders_createdbyuserid'), 'transactionheaders', ['createdbyuserid'], unique=False)
    op.create_index(op.f('ix_transactionheaders_createdon'), 'transactionheaders', ['createdon'], unique=False)
    op.create_index(op.f('ix_transactionheaders_postedbyuserid'), 'transactionheaders', ['postedbyuserid'], unique=False)
    op.create_index(op.f('ix_transactionheaders_postedon'), 'transactionheaders', ['postedon'], unique=False)
    op.create_index(op.f('ix_transactionheaders_event'), 'transactionheaders', ['event'], unique=False)
    op.create_index(op.f('ix_transactionlines_accountid'), 'transactionlines', ['accountid'], unique=False)
    op.create_index(op.f('ix_transactionlines_transactionheaderid'), 'transactionlines', ['transactionheaderid'], unique=False)
    op.alter_column('userpresentationcards', 'photocontenttype',
               existing_type=sa.TEXT(),
               nullable=True)
    
    op.execute("create extension pgstattuple;")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('userpresentationcards', 'photocontenttype',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_index(op.f('ix_transactionlines_transactionheaderid'), table_name='transactionlines')
    op.drop_index(op.f('ix_transactionlines_accountid'), table_name='transactionlines')
    op.drop_index(op.f('ix_transactionheaders_event'), table_name='transactionheaders')
    op.drop_index(op.f('ix_transactionheaders_postedon'), table_name='transactionheaders')
    op.drop_index(op.f('ix_transactionheaders_postedbyuserid'), table_name='transactionheaders')
    op.drop_index(op.f('ix_transactionheaders_createdon'), table_name='transactionheaders')
    op.drop_index(op.f('ix_transactionheaders_createdbyuserid'), table_name='transactionheaders')
    op.drop_index(op.f('ix_transactionheaders_contractid'), table_name='transactionheaders')
    op.execute("drop extension pgstattuple;")
    # ### end Alembic commands ###

