"""#310 create transaction header and lines tables

Revision ID: 53f7bfc7afb3
Revises: 3ca41b71a5d0
Create Date: 2026-02-15 13:27:22.366943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53f7bfc7afb3'
down_revision: Union[str, None] = '3ca41b71a5d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactionheaders',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('event', sa.String(length=60), nullable=False),
    sa.Column('createdon', sa.DateTime(), server_default=sa.text("(current_timestamp at time zone 'utc')"), nullable=False),
    sa.Column('createdbyuserid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['createdbyuserid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactionheaders_id'), 'transactionheaders', ['id'], unique=False)
    op.create_table('transactionlines',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('transactionheaderid', sa.UUID(), nullable=False),
    sa.Column('accountid', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('postedon', sa.DateTime(), nullable=True),
    sa.Column('postedbyuserid', sa.UUID(), server_default=sa.text('NULL'), nullable=True),
    sa.ForeignKeyConstraint(['accountid'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['postedbyuserid'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transactionheaderid'], ['transactionheaders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactionlines_id'), 'transactionlines', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactionlines_id'), table_name='transactionlines')
    op.drop_table('transactionlines')
    op.drop_index(op.f('ix_transactionheaders_id'), table_name='transactionheaders')
    op.drop_table('transactionheaders')
    # ### end Alembic commands ###
