"""#322 transactions link to contracts instead of the other way around

Revision ID: 5b7b52dbd99c
Revises: 10bebd9ef862
Create Date: 2026-03-02 16:23:29.215157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b7b52dbd99c'
down_revision: Union[str, None] = '10bebd9ef862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###


    op.add_column('transactionheaders', sa.Column('contractid', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'transactionheaders', 'contracts', ['contractid'], ['id'])

    op.execute("UPDATE transactionheaders th SET contractid = (SELECT id FROM contracts WHERE depositcollectedtransactionheaderid = th.id OR depositsettledtransactionheaderid = th.id);")

    op.drop_constraint('contracts_depositsettledtransactionheaderid_fkey', 'contracts', type_='foreignkey')
    op.drop_constraint('contracts_depositcollectedtransactionheaderid_fkey', 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'depositsettledtransactionheaderid')
    op.drop_column('contracts', 'depositcollectedtransactionheaderid')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactionheaders', type_='foreignkey')
    op.drop_column('transactionheaders', 'contractid')
    op.add_column('contracts', sa.Column('depositcollectedtransactionheaderid', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('contracts', sa.Column('depositsettledtransactionheaderid', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('contracts_depositcollectedtransactionheaderid_fkey', 'contracts', 'transactionheaders', ['depositcollectedtransactionheaderid'], ['id'])
    op.create_foreign_key('contracts_depositsettledtransactionheaderid_fkey', 'contracts', 'transactionheaders', ['depositsettledtransactionheaderid'], ['id'])
    # ### end Alembic commands ###
