"""#227 added colours and bike colours tables

Revision ID: 5eef3c406203
Revises: fa50787bdeca
Create Date: 2025-09-20 22:51:44.496549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5eef3c406203'
down_revision: Union[str, None] = 'fa50787bdeca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colours',
    sa.Column('id', sa.Integer(), server_default='0', nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_colours_id'), 'colours', ['id'], unique=False)
    op.create_table('bikecolours',
    sa.Column('bikeid', sa.UUID(), nullable=False),
    sa.Column('colourid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bikeid'], ['bikes.id'], ),
    sa.ForeignKeyConstraint(['colourid'], ['colours.id'], ),
    sa.PrimaryKeyConstraint('bikeid', 'colourid')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bikecolours')
    op.drop_index(op.f('ix_colours_id'), table_name='colours')
    op.drop_table('colours')
    # ### end Alembic commands ###
