"""#312 add flag for items being second hand

Revision ID: 616e4ec2b358
Revises: 0a0a38e50e42
Create Date: 2026-02-26 19:54:09.572491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '616e4ec2b358'
down_revision: Union[str, None] = '0a0a38e50e42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogueitems', sa.Column('issecondhand', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('catalogueitems', 'issecondhand')
    # ### end Alembic commands ###
