"""added account description

Revision ID: 6236a047c61d
Revises: 53f7bfc7afb3
Create Date: 2026-02-15 15:48:42.243943

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6236a047c61d'
down_revision: Union[str, None] = '53f7bfc7afb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accounts', sa.Column('description', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'description')
    # ### end Alembic commands ###
