"""renamed permissionScopes to permissions

Revision ID: 6a51824d29da
Revises: 62c8069043d3
Create Date: 2025-05-22 16:12:24.360421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a51824d29da'
down_revision: Union[str, None] = '62c8069043d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('route', sa.Text(), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('isendpoint', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_permissions_id'), 'permissions', ['id'], unique=False)
    op.drop_index('ix_permissionscopes_id', table_name='permissionscopes')
    op.drop_constraint('grouppermissions_permissionscopeid_fkey', 'grouppermissions', type_='foreignkey')
    op.drop_constraint('userpermissions_permissionscopeid_fkey', 'userpermissions', type_='foreignkey')
    op.drop_table('permissionscopes')
    op.add_column('grouppermissions', sa.Column('permissionid', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'grouppermissions', 'permissions', ['permissionid'], ['id'])
    op.drop_column('grouppermissions', 'permissionscopeid')
    op.add_column('userpermissions', sa.Column('permissionid', sa.UUID(), nullable=False))
    op.drop_index('ix_userpermissions_id', table_name='userpermissions')
    op.create_foreign_key(None, 'userpermissions', 'permissions', ['permissionid'], ['id'])
    op.drop_column('userpermissions', 'permissionscopeid')
    op.drop_column('userpermissions', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userpermissions', sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False))
    op.add_column('userpermissions', sa.Column('permissionscopeid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'userpermissions', type_='foreignkey')
    op.create_foreign_key('userpermissions_permissionscopeid_fkey', 'userpermissions', 'permissionscopes', ['permissionscopeid'], ['id'])
    op.create_index('ix_userpermissions_id', 'userpermissions', ['id'], unique=False)
    op.drop_column('userpermissions', 'permissionid')
    op.add_column('grouppermissions', sa.Column('permissionscopeid', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'grouppermissions', type_='foreignkey')
    op.create_foreign_key('grouppermissions_permissionscopeid_fkey', 'grouppermissions', 'permissionscopes', ['permissionscopeid'], ['id'])
    op.drop_column('grouppermissions', 'permissionid')
    op.create_table('permissionscopes',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), autoincrement=False, nullable=False),
    sa.Column('route', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('method', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('isendpoint', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='permissionscopes_pkey')
    )
    op.create_index('ix_permissionscopes_id', 'permissionscopes', ['id'], unique=False)
    op.drop_index(op.f('ix_permissions_id'), table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
