"""correct column name

Revision ID: 7fb9d13525d2
Revises: 09c70816ae58
Create Date: 2026-02-19 14:42:04.593082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fb9d13525d2'
down_revision: Union[str, None] = '09c70816ae58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contractdrafts', sa.Column('depositcollectedtransactionheaderid', sa.UUID(), nullable=True))
    op.drop_constraint('contractdrafts_depositcollectiontransactionheaderid_fkey', 'contractdrafts', type_='foreignkey')
    op.create_foreign_key(None, 'contractdrafts', 'transactionheaders', ['depositcollectedtransactionheaderid'], ['id'])
    op.drop_column('contractdrafts', 'depositcollectiontransactionheaderid')
    op.add_column('contracts', sa.Column('depositcollectedtransactionheaderid', sa.UUID(), nullable=True))
    op.drop_constraint('contracts_depositcollectiontransactionheaderid_fkey', 'contracts', type_='foreignkey')
    op.create_foreign_key(None, 'contracts', 'transactionheaders', ['depositcollectedtransactionheaderid'], ['id'])
    op.drop_column('contracts', 'depositcollectiontransactionheaderid')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('depositcollectiontransactionheaderid', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.create_foreign_key('contracts_depositcollectiontransactionheaderid_fkey', 'contracts', 'transactionheaders', ['depositcollectiontransactionheaderid'], ['id'])
    op.drop_column('contracts', 'depositcollectedtransactionheaderid')
    op.add_column('contractdrafts', sa.Column('depositcollectiontransactionheaderid', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'contractdrafts', type_='foreignkey')
    op.create_foreign_key('contractdrafts_depositcollectiontransactionheaderid_fkey', 'contractdrafts', 'transactionheaders', ['depositcollectiontransactionheaderid'], ['id'])
    op.drop_column('contractdrafts', 'depositcollectedtransactionheaderid')
    # ### end Alembic commands ###
