"""permissions have a parent

Revision ID: 81efbf98020a
Revises: 6a51824d29da
Create Date: 2025-05-23 15:47:25.317174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81efbf98020a'
down_revision: Union[str, None] = '6a51824d29da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('parentpermissionid', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'permissions', 'permissions', ['parentpermissionid'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'permissions', type_='foreignkey')
    op.drop_column('permissions', 'parentpermissionid')
    # ### end Alembic commands ###
