"""#229 add photos to contract

Revision ID: 9426f1d0102e
Revises: 36b6e0d60049
Create Date: 2026-08-15 23:10:43.757823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9426f1d0102e'
down_revision: Union[str, None] = '36b6e0d60049'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contractphotos',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('contractid', sa.UUID(), nullable=True),
    sa.Column('contenttype', sa.Text(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['contractid'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contractphotos_contractid'), 'contractphotos', ['contractid'], unique=False)
    op.create_index(op.f('ix_contractphotos_id'), 'contractphotos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contractphotos_id'), table_name='contractphotos')
    op.drop_index(op.f('ix_contractphotos_contractid'), table_name='contractphotos')
    op.drop_table('contractphotos')
    # ### end Alembic commands ###
