"""added client and bike creation date

Revision ID: 96eddbbce619
Revises: 00d7a9831de0
Create Date: 2025-08-09 15:52:11.413237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96eddbbce619'
down_revision: Union[str, None] = '00d7a9831de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bikes', sa.Column('createdon', sa.DateTime(), server_default=sa.text("(current_timestamp at time zone 'utc')"), nullable=False))
    op.add_column('clients', sa.Column('createdon', sa.DateTime(), server_default=sa.text("(current_timestamp at time zone 'utc')"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'createdon')
    op.drop_column('bikes', 'createdon')
    # ### end Alembic commands ###
