"""#164 added skeleton user group models and relationships

Revision ID: 994a225cf467
Revises: be5a603e248e
Create Date: 2025-05-21 16:07:59.810583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '994a225cf467'
down_revision: Union[str, None] = 'be5a603e248e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usergroups',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usergroups_id'), 'usergroups', ['id'], unique=False)
    op.create_table('usergroupusers',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('userid', sa.UUID(), nullable=False),
    sa.Column('usergroupid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['usergroupid'], ['usergroups.id'], ),
    sa.ForeignKeyConstraint(['userid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usergroupusers_id'), 'usergroupusers', ['id'], unique=False)
    op.create_table('usergrouppermissions',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('usergroupid', sa.UUID(), nullable=False),
    sa.Column('permissionscopeid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permissionscopeid'], ['permissionscopes.id'], ),
    sa.ForeignKeyConstraint(['usergroupid'], ['usergroups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usergrouppermissions_id'), 'usergrouppermissions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usergrouppermissions_id'), table_name='usergrouppermissions')
    op.drop_table('usergrouppermissions')
    op.drop_index(op.f('ix_usergoupusers_id'), table_name='usergoupusers')
    op.drop_table('usergoupusers')
    op.drop_index(op.f('ix_usergroups_id'), table_name='usergroups')
    op.drop_table('usergroups')
    # ### end Alembic commands ###
