"""Add FAQ table

Revision ID: a78b410a77ae
Revises: a3e4a6ebae58
Create Date: 2025-03-24 13:47:09.878266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a78b410a77ae'
down_revision: Union[str, None] = 'a3e4a6ebae58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faq',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('question', sa.String(length=256), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.Column('orderindex', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faq_id'), 'faq', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faq_id'), table_name='faq')
    op.drop_table('faq')
    # ### end Alembic commands ###
