"""added cancellation reason to appointment model

Revision ID: acee4bfb78e5
Revises: f23b82963317
Create Date: 2025-08-15 12:23:28.837424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acee4bfb78e5'
down_revision: Union[str, None] = 'f23b82963317'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('cancellationreason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'cancellationreason')
    # ### end Alembic commands ###
