"""#314 accounts can be restricted to a project

Revision ID: aef9aced5d15
Revises: fd5322d2a4ad
Create Date: 2026-02-19 21:18:06.583262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aef9aced5d15'
down_revision: Union[str, None] = 'fd5322d2a4ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('accounts', sa.Column('restrictedtoprojectid', sa.String(length=20), server_default=sa.text('NULL'), nullable=True))
    op.create_foreign_key(None, 'accounts', 'projects', ['restrictedtoprojectid'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'accounts', type_='foreignkey')
    op.drop_column('accounts', 'restrictedtoprojectid')
    op.drop_table('projects')
    # ### end Alembic commands ###
