"""#192 added crimereports table

Revision ID: b6e19fd0aee6
Revises: 2818f7b0c831
Create Date: 2025-08-31 13:03:01.657852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6e19fd0aee6'
down_revision: Union[str, None] = '2818f7b0c831'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crimereports',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('crimenumber', sa.String(length=40), nullable=False),
    sa.Column('contractid', sa.UUID(), nullable=False),
    sa.Column('createdon', sa.DateTime(), server_default=sa.text("(current_timestamp at time zone 'utc')"), nullable=False),
    sa.Column('closed', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False),
    sa.ForeignKeyConstraint(['contractid'], ['contracts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crimereports_id'), 'crimereports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crimereports_id'), table_name='crimereports')
    op.drop_table('crimereports')
    # ### end Alembic commands ###
