"""flag routes that are endpoints

Revision ID: be5a603e248e
Revises: 0787b049962a
Create Date: 2025-05-19 13:16:32.976386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be5a603e248e'
down_revision: Union[str, None] = '0787b049962a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissionscopes', sa.Column('isendpoint', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissionscopes', 'isendpoint')
    # ### end Alembic commands ###
