"""add lastauthenticated column to User table

Revision ID: c0dc35faf013
Revises: d0292fb9f1df
Create Date: 2025-05-09 08:39:57.483938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0dc35faf013'
down_revision: Union[str, None] = 'd0292fb9f1df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lastauthenticated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'lastauthenticated')
    # ### end Alembic commands ###
