"""#396 client anonymised flag

Revision ID: cfc27290d8b6
Revises: e66d8d1706ba
Create Date: 2026-06-03 16:32:17.751430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfc27290d8b6'
down_revision: Union[str, None] = 'e66d8d1706ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('anonymised', sa.Boolean(), nullable=False, default=False, server_default=sa.text('FALSE')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'anonymised')
    # ### end Alembic commands ###
