"""#297 tables for sale headers, item sale lines and bike sale lines

Revision ID: d4903d6a73db
Revises: 10bebd9ef862
Create Date: 2026-03-01 17:26:26.690784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4903d6a73db'
down_revision: Union[str, None] = '10bebd9ef862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saleheaders',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('createdon', sa.DateTime(), server_default=sa.text("(current_timestamp at time zone 'utc')"), nullable=False),
    sa.Column('createdbyuserid', sa.UUID(), nullable=False),
    sa.Column('transactionheaderid', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['createdbyuserid'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transactionheaderid'], ['transactionheaders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_saleheaders_id'), 'saleheaders', ['id'], unique=False)
    op.create_table('bikesalelines',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('saleheaderid', sa.UUID(), nullable=False),
    sa.Column('saleprice', sa.Integer(), nullable=False),
    sa.Column('bikeid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['bikeid'], ['bikes.id'], ),
    sa.ForeignKeyConstraint(['saleheaderid'], ['saleheaders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bikesalelines_id'), 'bikesalelines', ['id'], unique=False)
    op.create_table('catalogueitemsalelines',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('saleheaderid', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('saleprice', sa.Integer(), nullable=False),
    sa.Column('catalogueitemid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['catalogueitemid'], ['catalogueitems.id'], ),
    sa.ForeignKeyConstraint(['saleheaderid'], ['saleheaders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_catalogueitemsalelines_id'), 'catalogueitemsalelines', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_catalogueitemsalelines_id'), table_name='catalogueitemsalelines')
    op.drop_table('catalogueitemsalelines')
    op.drop_index(op.f('ix_bikesalelines_id'), table_name='bikesalelines')
    op.drop_table('bikesalelines')
    op.drop_index(op.f('ix_saleheaders_id'), table_name='saleheaders')
    op.drop_table('saleheaders')
    # ### end Alembic commands ###
