"""#420 basic chat data structure

Revision ID: d51a9a4492b1
Revises: 36eb89e30bbf
Create Date: 2026-09-19 15:13:53.447476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd51a9a4492b1'
down_revision: Union[str, None] = '36eb89e30bbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participants',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_participants_id'), 'participants', ['id'], unique=False)
    op.create_table('conversations',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('initiatorparticipantid', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['initiatorparticipantid'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('initiatorparticipantid')
    )
    op.create_index(op.f('ix_conversations_id'), 'conversations', ['id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
    sa.Column('conversationid', sa.UUID(), nullable=False),
    sa.Column('senton', sa.DateTime(), server_default=sa.text("(current_timestamp at time zone 'utc')"), nullable=False),
    sa.Column('sentbyparticipantid', sa.UUID(), nullable=False),
    sa.Column('seenbyparticipantid', sa.UUID(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['conversationid'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['seenbyparticipantid'], ['participants.id'], ),
    sa.ForeignKeyConstraint(['sentbyparticipantid'], ['participants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_senton'), 'messages', ['senton'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.add_column('clients', sa.Column('participantid', sa.UUID(), nullable=True))
    op.create_foreign_key("clients_participantid_fkey", 'clients', 'participants', ['participantid'], ['id'])
    op.add_column('users', sa.Column('participantid', sa.UUID(), nullable=True))
    op.create_foreign_key("users_participantid_fkey", 'users', 'participants', ['participantid'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("users_participantid_fkey", 'users', type_='foreignkey')
    op.drop_column('users', 'participantid')
    op.drop_constraint("clients_participantid_fkey", 'clients', type_='foreignkey')
    op.drop_column('clients', 'participantid')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_senton'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_conversations_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index(op.f('ix_participants_id'), table_name='participants')
    op.drop_table('participants')
    # ### end Alembic commands ###
