"""cascade delete bike duplicate when bike is deleted

Revision ID: e54aecec7d03
Revises: 4d56a78fc8bd
Create Date: 2025-08-09 17:38:12.140521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e54aecec7d03'
down_revision: Union[str, None] = '4d56a78fc8bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('detectedpotentialbikeduplicates_bike2id_fkey', 'detectedpotentialbikeduplicates', type_='foreignkey')
    op.drop_constraint('detectedpotentialbikeduplicates_bike1id_fkey', 'detectedpotentialbikeduplicates', type_='foreignkey')
    op.create_foreign_key(None, 'detectedpotentialbikeduplicates', 'bikes', ['bike2id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'detectedpotentialbikeduplicates', 'bikes', ['bike1id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'detectedpotentialbikeduplicates', type_='foreignkey')
    op.drop_constraint(None, 'detectedpotentialbikeduplicates', type_='foreignkey')
    op.create_foreign_key('detectedpotentialbikeduplicates_bike1id_fkey', 'detectedpotentialbikeduplicates', 'bikes', ['bike1id'], ['id'])
    op.create_foreign_key('detectedpotentialbikeduplicates_bike2id_fkey', 'detectedpotentialbikeduplicates', 'bikes', ['bike2id'], ['id'])
    # ### end Alembic commands ###
