"""#381 flag contracts that have been notified of dormant liability

Revision ID: e66d8d1706ba
Revises: 51e4fa786e3a
Create Date: 2026-04-12 00:10:01.992033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e66d8d1706ba'
down_revision: Union[str, None] = '51e4fa786e3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('liabilitydormantsent', sa.Boolean(), server_default=sa.text('FALSE'), nullable=False))
    op.execute("UPDATE contracts SET liabilitydormantsent = 't' WHERE id in (SELECT contractid FROM transactionheaders WHERE event = 'liability_dormant')")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contracts', 'liabilitydormantsent')
    # ### end Alembic commands ###
