"""#416 appointment show up status

Revision ID: e93a9bf1ed35
Revises: cfc27290d8b6
Create Date: 2026-08-09 17:23:12.841486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e93a9bf1ed35'
down_revision: Union[str, None] = 'cfc27290d8b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('didclientshowup', sa.Boolean(), server_default=sa.text('NULL'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'didclientshowup')
    # ### end Alembic commands ###
