"""create view to identify orphaned bikes

Revision ID: f23b82963317
Revises: 4700ed9e9e05
Create Date: 2025-08-09 17:47:00.166685

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f23b82963317'
down_revision: Union[str, None] = '4700ed9e9e05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""CREATE VIEW orphanedbikes AS SELECT b.id
FROM bikes b
LEFT JOIN (
	SELECT count(con.id) num
		,con.bikeid
	FROM contracts con
	GROUP BY con.bikeid
	) concounts ON concounts.bikeid = b.id
LEFT JOIN (
	SELECT count(condraft.id) num
		,condraft.bikeid
	FROM contractdrafts condraft
	GROUP BY condraft.bikeid
	) condraftcounts ON condraftcounts.bikeid = b.id
WHERE
	concounts.num IS NULL AND
	condraftcounts IS NULL;""")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW orphanedbikes;")
    # ### end Alembic commands ###
