"""#226 added ordering to appointment types

Revision ID: fa50787bdeca
Revises: 29519339abb4
Create Date: 2025-09-14 16:39:59.701066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fa50787bdeca'
down_revision: Union[str, None] = '29519339abb4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointmenttypes', sa.Column('orderindex', sa.Integer(), sa.Identity(always=False, start=1, cycle=True), nullable=False))
    op.create_index(op.f('ix_appointmenttypes_orderindex'), 'appointmenttypes', ['orderindex'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointmenttypes_orderindex'), table_name='appointmenttypes')
    op.drop_column('appointmenttypes', 'orderindex')
    # ### end Alembic commands ###
