"""#309 migrate existing contracts deposit info

Revision ID: fd5322d2a4ad
Revises: 7fb9d13525d2
Create Date: 2026-02-19 14:43:04.103644

"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text
from datetime import datetime


# revision identifiers, used by Alembic.
revision: str = 'fd5322d2a4ad'
down_revision: Union[str, None] = '7fb9d13525d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    db = op.get_bind()


    treasurer_user_group_id = db.execute(text("SELECT ID FROM groups where name = 'treasurers';")).first()[0]

    db.execute(text(f"INSERT INTO accounts "
                    f"(name, type, description, ownergroupid, isinternal) "
                    f"VALUES "
                    f"('bank deposit stash', 'asset', 'Bike deposits in the bank', '{treasurer_user_group_id}', true);"))
    
    deposit_bearer_group_id = db.execute(text("SELECT ID FROM groups where name = 'deposit bearers';")).first()[0]
    
    db.execute(text(f"INSERT INTO accounts "
               f"(name, type, description, ownergroupid, isinternal) "
               f"VALUES "
               f"('active bike deposits', 'liability', 'Active deposits for bikes', '{deposit_bearer_group_id}', true);"))
    
    
    deposit_liability_account_id = db.execute(text("SELECT ID FROM accounts where name = 'active bike deposits';")).first()[0]

    db.execute(text(f"INSERT INTO accounts "
                    f"(name, type, description, ownergroupid, isinternal) "
                    f"VALUES "
                    f"('forfeited deposit income', 'revenue', 'This is where forfeited deposits are recorded', '{deposit_bearer_group_id}', true);"))


    deposit_forfeit_revenue_account_id = db.execute(text("SELECT ID FROM accounts where name = 'forfeited deposit income';")).first()[0]

    for contract in db.execute(text("SELECT "
                                "id"
                                    ", depositamountcollected"
                                    ", depositcollectinguserid"
                                    ", startdate"
                                    ", depositamountreturned"
                                    ", depositreturninguserid"
                                    ", returneddate "
                                    "FROM contracts "
                                    "WHERE "
                                    "depositamountcollected IS NOT NULL;")):
        contract_id = contract[0]
        deposit_amount_collected = contract[1]
        deposit_collecting_user_id = contract[2]
        start_date = contract[3]
        deposit_amount_returned = contract[4]
        deposit_returning_user_id = contract[5]
        returned_date = contract[6]
        
        deposit_collector_account_search = db.execute(text(f"SELECT id FROM accounts where owneruserid='{deposit_collecting_user_id}' AND type='asset' AND name LIKE '%deposit%';"))
        
        if deposit_collector_account_search.rowcount == 0:
            username = db.execute(text(f"SELECT username FROM users where id='{deposit_collecting_user_id}';")).first()[0]
            db.execute(text(f"INSERT INTO accounts "
                            f"(name, owneruserid, type, isinternal, description) "
                            f"VALUES "
                            f"('{username} deposit stash', '{deposit_collecting_user_id}', 'asset', true, 'Deposit stash for {username}');"))
            deposit_collector_account_search = db.execute(text(f"SELECT id FROM accounts where owneruserid='{deposit_collecting_user_id}' AND type='asset' AND name LIKE '%deposit%';"))

        deposit_collector_account_id = deposit_collector_account_search.first()[0]
            
        deposit_collected_transaction_header_id = uuid.uuid4()
        db.execute(text(f"INSERT INTO transactionheaders "
                        f"(id, event, createdon, createdbyuserid, postedon, postedbyuserid) "
                        f"VALUES "
                        f"('{deposit_collected_transaction_header_id}', "
                        f"'deposit_collected', "
                        f"'{datetime(start_date.year, start_date.month, start_date.day, 17, 0, 0)}', "
                        f"'{deposit_collecting_user_id}', "
                        f"'{datetime(start_date.year, start_date.month, start_date.day, 17, 0, 0)}', "
                        f"'{deposit_collecting_user_id}');"))
        
        db.execute(text(f"INSERT INTO transactionlines (transactionheaderid, accountid, amount) "
                        f"VALUES "
                        f"('{deposit_collected_transaction_header_id}', '{deposit_liability_account_id}', {-deposit_amount_collected * 100}), "
                        f"('{deposit_collected_transaction_header_id}' ,'{deposit_collector_account_id}', {deposit_amount_collected * 100});"))
            
        db.execute(text(f"UPDATE contracts SET depositcollectedtransactionheaderid = '{deposit_collected_transaction_header_id}' WHERE id = '{contract_id}';"))
            
        if returned_date is not None:
            deposit_returner_account_search = db.execute(text(f"SELECT id FROM accounts where owneruserid='{deposit_returning_user_id}' AND type='asset' AND name LIKE '%deposit%';"))

            if deposit_returner_account_search.rowcount == 0:
                username = db.execute(text(f"SELECT username FROM users where id='{deposit_returning_user_id}';"))
                db.execute(text(f"INSERT INTO accounts "
                                f"(name, owneruserid, type, isinternal, description) "
                                f"VALUES "
                                f"('{username} deposit stash', '{deposit_returning_user_id}', 'asset', true, 'Deposit stash for {username}');"))
                deposit_returner_account_search = db.execute(text(f"SELECT id FROM accounts where owneruserid='{deposit_returning_user_id}' AND type='asset' AND name LIKE '%deposit%';"))
    
            deposit_returner_account_id = deposit_returner_account_search.first()[0]

            deposit_settled_transaction_header_id = uuid.uuid4()
            db.execute(text(f"INSERT INTO transactionheaders "
                            f"(id, event, createdon, createdbyuserid, postedon, postedbyuserid) "
                            f"VALUES "
                            f"('{deposit_settled_transaction_header_id}', "
                            f"'deposit_settled', "
                            f"'{datetime(returned_date.year, returned_date.month, returned_date.day, 18, 0, 0)}', "
                            f"'{deposit_returning_user_id}', "
                            f"'{datetime(returned_date.year, returned_date.month, returned_date.day, 18, 0, 0)}', "
                            f"'{deposit_returning_user_id}');"))
            
            db.execute(text(f"INSERT INTO transactionlines (transactionheaderid, accountid, amount) "
                            f"VALUES "
                            f"('{deposit_settled_transaction_header_id}', '{deposit_liability_account_id}', {deposit_amount_collected * 100}), "
                            f"('{deposit_settled_transaction_header_id}' ,'{deposit_returner_account_id}', {-deposit_amount_returned * 100});"))
            if deposit_amount_returned < deposit_amount_collected:
                db.execute(text(f"INSERT INTO transactionlines (transactionheaderid, accountid, amount) "
                                f"VALUES "
                                f"('{deposit_settled_transaction_header_id}', '{deposit_forfeit_revenue_account_id}', {-((deposit_amount_collected - deposit_amount_returned) * 100)});"))
                
            db.execute(text(f"UPDATE contracts SET depositsettledtransactionheaderid = '{deposit_settled_transaction_header_id}' WHERE id = '{contract_id}';"))
                
                
    for exchange in db.execute(text("SELECT date, fromuserid, touserid, amount FROM depositexchanges;")):
        exchange_date = exchange[0]
        from_user_id = exchange[1]
        to_user_id = exchange[2]
        amount = exchange[3]
        
        deposit_exchange_transaction_header_id = uuid.uuid4()
        db.execute(text(f"INSERT INTO transactionheaders "
                        f"(id, event, createdon, createdbyuserid, postedon, postedbyuserid) "
                        f"VALUES "
                        f"('{deposit_exchange_transaction_header_id}', "
                        f"'deposit_exchanged', "
                        f"'{datetime(exchange_date.year, exchange_date.month, exchange_date.day, 19, 0, 0)}', "
                        f"'{from_user_id}', "
                        f"'{datetime(exchange_date.year, exchange_date.month, exchange_date.day, 19, 0, 0)}', "
                        f"'{to_user_id}');"
        ))
        
        from_username = db.execute(text(f"SELECT username FROM users where id='{from_user_id}';")).first()[0]
        to_username = db.execute(text(f"SELECT username FROM users where id='{to_user_id}';")).first()[0]
        
        from_account_id = None
        to_account_id = None
        if from_username.lower() == "bank":
            from_account_id = db.execute(text(f"SELECT id FROM accounts where name='bank deposit stash';")).first()[0]
        else:
            from_account_id = db.execute(text(f"SELECT id FROM accounts where owneruserid='{from_user_id}' AND type='asset' AND name LIKE '%deposit%';")).first()[0]
            
        if to_username.lower() == "bank":
            to_account_id = db.execute(text(f"SELECT id FROM accounts where name='bank deposit stash';")).first()[0]
        else:
            to_account_id = db.execute(text(f"SELECT id FROM accounts where owneruserid='{to_user_id}' AND type='asset' AND name LIKE '%deposit%';")).first()[0]
            
        db.execute(text(f"INSERT INTO transactionlines (transactionheaderid, accountid, amount) "
                        f"VALUES "
                        f"('{deposit_exchange_transaction_header_id}', '{from_account_id}', {-amount * 100}), "
                        f"('{deposit_exchange_transaction_header_id}' ,'{to_account_id}', {amount * 100});"))

# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE contracts SET depositcollectedtransactionheaderid = NULL, depositsettledtransactionheaderid = NULL;")
    op.execute("DELETE FROM transactionlines; DELETE FROM transactionheaders;")
    op.execute("DELETE FROM accounts;")
    # ### end Alembic commands ###
