"""#391 attach sale to contract during draft stage

Revision ID: fe875a937c20
Revises: 337edae0bdee
Create Date: 2026-09-08 21:44:28.597958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe875a937c20'
down_revision: Union[str, None] = '337edae0bdee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('saleheaderid', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'contracts', 'saleheaders', ['saleheaderid'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'saleheaderid')
    # ### end Alembic commands ###
