from .admin import admin
from .appointments import appointments
from .bikes import bikes
from .clients import clients
from .contracts import contracts
from .depositExchanges import deposit_exchanges
from .finances import finances
from .maps import maps
from .public import public
from .settings import settings
from .statistics import statistics
from .users import users
from .expenses import expenses
from .groups import groups
from .clientsMe import clients_me
from .clientsPublic import public_clients
from .appointmentsPublic import appointments_public
from .usersPublic import users_public
from .crimeReports import crime_reports
from .colours import colours
